### ISSUE TITLE
Error en volumenes de odoo

### ISSUE THREAD

**Issue by setterlee** [bmya/odoo-docker-scripts#1]
en el script doeall se mapea el volumen del contenedor "/opt/odoo/.filestore" a la ruta del host "/opt/odoo/.filestore" pero en el script install.sh se crea el directorio /opt/odoo/.filelocal en la línea 8 en vez de crear "/opt/odoo/.filestore"

**Comment by Danisan** [comment]
bien. gracias por el error. Se corregirá en breve
