### ISSUE TITLE
install.sh no ejecuta creación de perfil de BD odoo

### ISSUE THREAD

**Issue by setterlee** [bmya/odoo-docker-scripts#2]
Al intentar ejecutar el comando para crear el perfil de usuario odoo en base de datos, la consola retorna un error indicando que no pudo conectarse a la bd, posiblemente se trate de que se ejecuta muy rapido sin esperar que el contenedor levante la base de datos.

**Comment by Danisan** [comment]
Es posible. Prueba agregar una pausa en la ejecución, o bien parametrizar el usuario desde la linea de arranque del contenedor de base de datos, similar a como se puede ver acá:

docker run -d --restart=always -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo \
 -p 5433:5432 \
 -v /opt/database9:/var/lib/postgresql/data \
 -v /var/log/postgresql9:/var/log/postgresql \
 --name db postgres:9.4
